---
- hosts: localhost
  become: yes
  tasks:
         - name: update all package
           apt:
               name: '*'
               state: latest
         
         - name: deploy compose
           shell: docker-compose up -d
         
         - name: display
           shell: docker-compose ps
           register: xyz

      
         - debug: 
               msg: "value of xyz is: {{ xyz.stdout_lines }}"
