---
- hosts: localhost
  become_user: jenkins
  tasks:
         - name: update all package
           apt:
               name: '*'
               state: latest
         
         - name: deploy compose
           command: bash deploy.sh
         
         - name: display
           shell: docker-compose ps
           register: xyz

      
         - debug: 
               msg: "value of xyz is: {{ xyz.stdout_lines }}"
